steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker login --username=$$USERNAME --password=$$PASSWORD']
  secretEnv: ['USERNAME', 'PASSWORD']
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker build -t $$USERNAME/bliba-prompt:0.0.8 .']
  secretEnv: ['USERNAME']
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker push $$USERNAME/bliba-prompt:0.0.8']
  secretEnv: ['USERNAME']
availableSecrets:
  secretManager:
  - versionName: projects/48574477087/secrets/docker-password/versions/1
    env: 'PASSWORD'
  - versionName: projects/48574477087/secrets/docker-username/versions/1
    env: 'USERNAME'
options:
  logging: CLOUD_LOGGING_ONLY