services:
  prompt:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - HUGGINGFACE_ACCESS_TOKEN=${HUGGINGFACE_ACCESS_TOKEN}
    ports: 
      - "8188:8188"
      - "8000:8000"
    volumes:
      - output:/comfyui/output
      #- /Volumes/HD 2TB/2 - REICA/models:/comfyui/models/
    environment:
      - SERVE_API_LOCALLY=true
volumes:
  output: